### PR TITLE
WIP: increased coverage for components

### LINKED ISSUE #145: 100% Jest Test coverage
- Create additional tests in the `/src/__tests__` folder, using Jest.  
- Run existing tests using `npm run test`
- Check coverage status using `npm run coverage`

Although check coverage should be 100%, it's ok if it's a little lower if only certain things are omitted (third party libraries, constants, in-line styling, or other piece with a valid reason not to test).

### PR DESCRIPTION
**Pull request by evgeniuz**
Fixes #145

### CODE REVIEW

**Comment by evgeniuz** [comment]
Please, do not merge this yet.

Increased test coverage for components a lot, also added few common things to `setupTests`, to make tests a bit less verbose. There are still things I would like to organise a bit (like move fixture out of Root :smiley:) and there are few unresolved issues with async component methods that are not fully covered. After these are resolved it may be merged.

I've used fixture with sample "hydrated" app state, which can be useful for many current tests, future tests and it can be extended when app is developed. Basically, my idea is that desired test state can be achieved either by loading empty store or by loading fixture and then altering it through `store.dispatch`.

Also, enzyme doesn't call set props on update, so to test componentWillReceiveProps it is necessary to set them through `wrapper.setProps`. If we use action to change them in store, enzyme will just create component anew instead of setting it's props (and calling componentWillReceiveProps).

**Comment by themandalore** [comment]
Thanks for the updates.  Feel free to reach out if you have any questions.  They're looking really good and I like the direction you're taking

**Comment by evgeniuz** [comment]
Components now have almost 100% coverage, plan to add few more assertions in some places and should be ready to merge. Only two components without 100%:

- requireComponent - not sure how to dive() into it to check component that it returns;
- PriceChart - this needs mock of Highcharts, which doesn't seem to work for me right now.

I'll try to fix those after actions/api/ethereum coverage, as they take too much time :)

**Comment by themandalore** [comment]
It's looking great. Let me know when you think it's ready to merge / play around with

**Comment by evgeniuz** [comment]
@themandalore component tests are covered 100%, this one is ready to merge. Will proceed with other tests now (some of the actions are also broken because of send funds removal, will fix that as well.

**Comment by themandalore** [comment]
Awesome stuff.  Thanks for the quick work @evgeniuz .  Also, be sure to pull down the most recent dev branch, some things have been updated

**Pull request merged**
